### PR TITLE
Add basic Plausible support

### PR DESCRIPTION
**Pull request by ProfHercules**

### CODE REVIEW

**Comment by dlecan** [comment]
@RatanShreshtha instead of having multiple analytics blocks in `base` (and so many tools to integrate :grin:), would you be interested in a generic block to be overloaded?
Like this one
https://github.com/dlecan/dlecan-zola-theme/blob/main/templates/base.html#L49-L61

GA would stay the default analytics tool, but anyone would replace it by its own tool simply by [overloding a Zola block ](https://www.getzola.org/documentation/themes/extending-a-theme/#overriding-a-block)

What do you think of this proposal @ProfHercules?

**Comment by ProfHercules** [comment]
I like the flexibility provided by the generic block, but I also enjoy the simplicity of just modifying a config value.

I'm not sure a use case exists for it, but using the config value also allows the theme to support multiple concurrent analytics systems simultaneously (maybe you prefer GA, but if a user blocks it you would still like some general stats from Plausible?).

A generic block is likely the right solution here - it enables the theme to support a default config and allows the user to override if they wish. 

Would you open the PR for this suggestion @dlecan? If so, I'll happily close this issue.

**Comment by dlecan** [comment]
> Would you open the PR for this suggestion @dlecan?

See #55

**Comment by ProfHercules** [comment]
Closing in favour of #55

**Pull request closed without merging**
